# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-24 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_featured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Productss',
        ),
    ]
