# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-24 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190524_0926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productss',
            new_name='Product',
        ),
    ]
